import { Request, Response, NextFunction } from 'express';
import jwt from 'jsonwebtoken';
import { AuthenticationError } from './errors';
import { User } from '../models/User';

export interface JwtPayload {
  userId: string;
  email: string;
  role: string;
}

declare global {
  namespace Express {
    interface Request {
      user?: JwtPayload;
    }
  }
}

/**
 * Authenticate the request via either:
 *   - Authorization: Bearer <jwt>      (web UI, default)
 *   - X-API-Token: <api_token>         (Chrome extension, scripted clients)
 *
 * API tokens are long-lived per-user secrets stored in users.api_token,
 * generated by an admin via the rotate-api-token script. They bypass the
 * JWT expiry cycle so the extension doesn't need a refresh flow.
 */
export async function authenticate(req: Request, _res: Response, next: NextFunction) {
  // Check API token header first -- short-circuit on match.
  const apiTokenHeader = req.headers['x-api-token'];
  if (typeof apiTokenHeader === 'string' && apiTokenHeader.length > 0) {
    try {
      const user = await User.findOne({ where: { api_token: apiTokenHeader } });
      if (!user) return next(new AuthenticationError('Invalid API token'));
      if (user.status !== 'active') return next(new AuthenticationError('User not active'));
      req.user = { userId: user.id, email: user.email, role: user.role };
      return next();
    } catch (e) {
      return next(new AuthenticationError('API token lookup failed'));
    }
  }

  // Fall back to JWT (existing behavior).
  const authHeader = req.headers.authorization;
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    return next(new AuthenticationError('No token provided'));
  }

  const token = authHeader.substring(7);

  try {
    const secret = process.env.JWT_SECRET;
    if (!secret) {
      return next(new AuthenticationError('Server configuration error'));
    }

    const decoded = jwt.verify(token, secret) as JwtPayload;
    req.user = decoded;
    next();
  } catch (error) {
    if (error instanceof jwt.TokenExpiredError) {
      return next(new AuthenticationError('Token expired'));
    }
    if (error instanceof jwt.JsonWebTokenError) {
      return next(new AuthenticationError('Invalid token'));
    }
    next(new AuthenticationError('Authentication failed'));
  }
}
