// Verifies the per-user states[] filter in listLeads (2026-06-14 refactor:
// replaced the 3-value territory_default enum with an N-state array so the
// model scales to per-location ownership: Percy TX, Iowa owner IA, future +).
// The actual SQL is generated by Sequelize, so we mock Lead.findAndCountAll
// and assert the right `where` shape is built.

jest.mock('../../models/Lead', () => ({
  Lead: { findAndCountAll: jest.fn() },
  PIPELINE_ORDER: {},
  PIPELINE_STAGES: [],
}));
jest.mock('../../services/leadScoringService', () => ({
  calculateLeadScore: jest.fn(),
  getLeadTemperature: jest.fn(),
}));

import { Op } from 'sequelize';
import { listLeads, buildStatesPattern, parseStatesParam } from '../../services/leadService';
import { Lead } from '../../models/Lead';

const mockFind = Lead.findAndCountAll as jest.Mock;

describe('listLeads states filter', () => {
  beforeEach(() => {
    jest.clearAllMocks();
    mockFind.mockResolvedValue({ count: 0, rows: [] });
  });

  it('does not add a state predicate when states is omitted', async () => {
    await listLeads({});
    const call = mockFind.mock.calls[0][0];
    expect(call.where.state).toBeUndefined();
  });

  it('does not add a state predicate when states is empty (sees all)', async () => {
    await listLeads({ states: [] });
    const call = mockFind.mock.calls[0][0];
    expect(call.where.state).toBeUndefined();
  });

  it('adds an iRegexp matcher for a single state', async () => {
    await listLeads({ states: ['TX'] });
    const call = mockFind.mock.calls[0][0];
    expect(call.where.state).toEqual({ [Op.iRegexp]: '^(TX|texas)$' });
  });

  it('adds a multi-state iRegexp when multiple states are passed', async () => {
    await listLeads({ states: ['TX', 'IA'] });
    const call = mockFind.mock.calls[0][0];
    expect(call.where.state).toEqual({ [Op.iRegexp]: '^(TX|texas|IA|iowa)$' });
  });

  it('still accepts an explicit state filter when states is not set', async () => {
    await listLeads({ state: 'CA' });
    const call = mockFind.mock.calls[0][0];
    expect(call.where.state).toEqual({ [Op.iLike]: 'CA' });
  });

  it('states scope overrides explicit state filter when both are set', async () => {
    await listLeads({ state: 'CA', states: ['TX'] });
    const call = mockFind.mock.calls[0][0];
    expect(call.where.state).toEqual({ [Op.iRegexp]: '^(TX|texas)$' });
  });
});

describe('buildStatesPattern', () => {
  it('includes both the 2-letter code and the full name when known', () => {
    expect(buildStatesPattern(['TX'])).toBe('^(TX|texas)$');
    expect(buildStatesPattern(['IA'])).toBe('^(IA|iowa)$');
  });

  it('falls back to just the code for states not in the known list', () => {
    expect(buildStatesPattern(['ZZ'])).toBe('^(ZZ)$');
  });

  it('joins multiple states with |', () => {
    expect(buildStatesPattern(['TX', 'IA', 'OK'])).toBe('^(TX|texas|IA|iowa|OK|oklahoma)$');
  });
});

describe('parseStatesParam', () => {
  it('parses a comma-separated string', () => {
    expect(parseStatesParam('TX,IA')).toEqual(['TX', 'IA']);
  });

  it('trims whitespace in comma-separated input', () => {
    expect(parseStatesParam('TX, IA, OK')).toEqual(['TX', 'IA', 'OK']);
  });

  it('passes through an array as-is, dropping non-string entries', () => {
    expect(parseStatesParam(['TX', 'IA'])).toEqual(['TX', 'IA']);
    expect(parseStatesParam(['TX', 42 as unknown as string])).toEqual(['TX']);
  });

  it('returns undefined for empty, null, undefined', () => {
    expect(parseStatesParam('')).toBeUndefined();
    expect(parseStatesParam(null)).toBeUndefined();
    expect(parseStatesParam(undefined)).toBeUndefined();
  });
});
